### ISSUE TITLE
Document rules which users would probably want to disable for templates

### ISSUE THREAD

**Issue by captbaritone** [platinumazure/eslint-plugin-microtemplates#3]
```
{
    "rules": {
        "no-undef": 0,
        "no-trailing-spaces": 0,
        "semi": 0
    }
}
```

**Comment by platinumazure** [comment]
Good call, I can do this fairly easily.

I was thinking of adding support pretty soon for a plugin setting that would allow users to suppress rules of their choosing for templates.

**Comment by platinumazure** [comment]
Oh, one more thing to note, I believe I can trim leading and trailing whitespace from extracted code while still preserving correct column information. If I can do that correctly, then `no-trailing-spaces` might perhaps be removed from the list above.

Thanks for trying the plugin out and for reporting these issues!

**Comment by platinumazure** [comment]
Say, @captbaritone, any chance you could give me an example of why you needed to disable `semi`?

**Comment by captbaritone** [comment]
Thanks for asking. I saw so many errors when I linted our templates that I didn't even look into what they looked like. Turns out, it's probably just a style thing for us. We seem to not bother putting semicolons at the end of single statements inside template strings:

```
<%- myFunc(myVar) %>
```

Probably not worth calling out as a special case, as some people may want to enforce putting semicolons there. If you can trim white space, that will mean the only real rule you need to ignore is `no-undef`.

**Comment by platinumazure** [comment]
Wait, you need a semicolon for an escape/interpolate case? That does sound
like a potential bug. What I would have expected as a legitimate lint error
would be a code execution:

`<% _.extend(myObj, anotherObj); // semi needed here %>`

If you can give me a repro for interpolate or escape where a semi was
incorrectly flagged, let me know. Thanks!

**Comment by captbaritone** [comment]
Sorry for missing that. In an attempt to generalize my example I used the wrong template string. Actual example:

```
<% print(createEmailTags(toEmail).join(', ')) %>
```

^ Not sure why we would do it that way... `git blame`.

**Comment by platinumazure** [comment]
Got it... Yeah, I'd say it's up to your workplace or repo maintainer or style guide and that allowing semi to be turned off for templates could make sense on a case by case basis. So hopefully when we get rule suppression support in, all will be well.

Thanks very much for taking the time to dig in.

**Comment by captbaritone** [comment]
My pleasure.

**Comment by platinumazure** [comment]
@captbaritone Okay, here's what I'm going to do. I'm accepting this issue and updating the README just to mention that some rules might need to be disabled for files linted by this plugin for now (and the change to do that will close this issue).

I probably will NOT include semi at this point. I'll include no-undef and no-trailing-spaces. If you have any other suggestions for common false positives, let me know and I'll add those.

Then I'm going to create some issues for the things I've identified above. For no-undef I'll create an issue saying we want to be able to suppress rules in the plugin (which is blocked by ESLint). For no-trailing-spaces I'll create an issue about trimming code (which isn't blocked). As I implement those features, I'll remove those rules from the "rules to disable" list.

Sound good?

**Comment by captbaritone** [comment]
Sounds good!
