### ISSUE TITLE
Allow no-trailing-spaces by trimming up to one space in extractor

### ISSUE THREAD

**Issue by platinumazure** [platinumazure/eslint-plugin-microtemplates#6]
Right now, it's impossible to have space in delimited blocks and enable `no-trailing-spaces`. Goal is to support a minimal trim for this use case.

Further enhancement will be needed, but that is blocked by eslint/eslint#5136.

**Comment by platinumazure** [comment]
@captbaritone I've pushed a new branch "trim-matched-code". To be honest, this implementation just does a standard String#trim() on the matched code and adjusts indexes accordingly, rather than anything complicated. Would you mind trying it out and seeing if it will allow for `no-trailing-spaces` without introducing new problems? Thanks!

**Comment by captbaritone** [comment]
Gave it a try. I was able to successfully remove our `no-trailing-spaces` exception for our templates dir. No errors were triggered.

**Comment by platinumazure** [comment]
@captbaritone :+1: Awesome! I also had a successful run on my codebase. I'd like to merge that into master-- if you have any objections, speak soon or forever hold your peace.

**Comment by captbaritone** [comment]
lgtm

**Comment by platinumazure** [comment]
Oh, and I'll remove `no-trailing-spaces` from my false positive list in README. Between that and doing some basic maintenance (mostly upgrading the ESLint devDependency and enabling rules to fit my preferred coding style), I should be able to cut 0.2.0 this weekend.

Thanks a lot for your help!

**Comment by captbaritone** [comment]
My pleasure. This plugin has greatly increased my confidence in the integrity of the JS in our templates. We run it as part of our commit hooks as well as our integration tests.
